### ISSUE TITLE
Files starting with a dot are not copied

### ISSUE THREAD

**Issue by fxaviersala** [pulumi/pulumi-synced-folder#12]
### What happened?

I was trying to sync a folder that contains a file that starts with a dot (to make it invisible on Linux).

The file was not copied to the Storage Account

### Expected Behavior

The file must be copied

### Steps to reproduce

Get the example project. `synced-folder-azure-csharp`. Put a file starting with a dot: `.env` and run pulumi.

The file is not showed in the preview:

![imatge](https://user-images.githubusercontent.com/44464869/215998036-13d64329-3be1-42d4-afd6-9e3e9d6735dd.png)

And, of course, is not copied to the BlobContainer.

### Output of `pulumi about`

running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  synced-folder-azure-csharp -> C:\tmp\pulumi-synced-folder\examples\synced-folder-azure-csharp\bin\Debug\net6.0\synced-folder-azure-csharp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.19

'dotnet build -nologo .' completed successfully
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
CLI
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.12.1
azure-native   1.93.0
dotnet         unknown
synced-folder  0.0.9

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.102'

Current Stack: patata

Found no resources associated with patata

Found no pending operations associated with patata

Backend
Name           Machine
URL            file://~
User           user
Organizations

Dependencies:
NAME                 VERSION
Pulumi               3.53.0
Pulumi.AzureNative   1.93.0
Pulumi.SyncedFolder  0.0.9

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pierskarsenbarg** [comment]
We use the glob npm package to grab the names of all the files. Looks like we're not handling dotfiles. I'm putting together a PR that should fix this.
