### ISSUE TITLE
pulumi-synced-folder Component triggers macOS firewall prompts

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-synced-folder#2]
### What happened?

When using a program that includes/uses/leverages the pulumi-synced-folder component on a macOS-based system with the firewall enabled, running a `pulumi up` or a `pulumi destroy` triggers a series of prompts from the macOS firewall to enable the component to listen to network traffic.

A similar issue was uncovered in core Pulumi and addressed in this PR: https://github.com/pulumi/pulumi/pull/10498

### Steps to reproduce

1. Create a new Pulumi project from one of the static website or serverless templates (both of which leverage the pulumi-synced-folder component).
2. Ensure the macOS firewall is enabled.
3. Run `pulumi up`; you should get a prompt asking if you want to allow pulumi-synced-folder to listen to network connections. Clicking Deny will still allow Pulumi and the program to finish successfully.

### Expected Behavior

Running a Pulumi program should not trigger a firewall warning to allow a component to accept incoming network traffic.

### Actual Behavior

Running a Pulumi program that includes the pulumi-synced-folder component triggers a macOS prompt to allow the component to accept inbound network traffic.

### Output of `pulumi about`

CLI
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME           VERSION
aws            5.16.0
gcp            6.39.0
nodejs         unknown
synced-folder  0.0.8

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in nodejs: executable='/Users/slowe/.nvm/versions/node/v16.17.0/bin/node' version='v16.17.0'

Current Stack: ts-dev

TYPE                                                    URN
pulumi:pulumi:Stack                                     urn:pulumi:ts-dev::test::pulumi:pulumi:Stack::test-ts-dev
pulumi:providers:gcp                                    urn:pulumi:ts-dev::test::pulumi:providers:gcp::default_6_39_0
gcp:storage/bucket:Bucket                               urn:pulumi:ts-dev::test::gcp:storage/bucket:Bucket::app-bucket
gcp:storage/bucket:Bucket                               urn:pulumi:ts-dev::test::gcp:storage/bucket:Bucket::site-bucket
gcp:storage/bucketObject:BucketObject                   urn:pulumi:ts-dev::test::gcp:storage/bucketObject:BucketObject::app-archive
pulumi:providers:synced-folder                          urn:pulumi:ts-dev::test::pulumi:providers:synced-folder::default_0_0_8
synced-folder:index:GoogleCloudFolder                   urn:pulumi:ts-dev::test::synced-folder:index:GoogleCloudFolder::synced-folder
pulumi:providers:gcp                                    urn:pulumi:ts-dev::test::pulumi:providers:gcp::default_6_35_0
gcp:storage/bucketObject:BucketObject                   urn:pulumi:ts-dev::test::synced-folder:index:GoogleCloudFolder$gcp:storage/bucketObject:BucketObject::index.html
gcp:storage/bucketObject:BucketObject                   urn:pulumi:ts-dev::test::synced-folder:index:GoogleCloudFolder$gcp:storage/bucketObject:BucketObject::error.html
gcp:storage/bucketIAMBinding:BucketIAMBinding           urn:pulumi:ts-dev::test::gcp:storage/bucketIAMBinding:BucketIAMBinding::site-bucket-iam-binding
gcp:cloudfunctions/function:Function                    urn:pulumi:ts-dev::test::gcp:cloudfunctions/function:Function::data-function
gcp:storage/bucketObject:BucketObject                   urn:pulumi:ts-dev::test::gcp:storage/bucketObject:BucketObject::site-config
gcp:cloudfunctions/functionIamMember:FunctionIamMember  urn:pulumi:ts-dev::test::gcp:cloudfunctions/functionIamMember:FunctionIamMember::data-function-invoker

Found no pending operations associated with ts-dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/scottslowe
User           scottslowe
Organizations  scottslowe

Pulumi locates its logs in /var/folders/kp/nk2y9x1x13n6v6r_d1wqhztm0000gn/T/ by default

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
If the @pulumi/pulumi dependency (or equivalent) is updated here, you should no longer see this.

**Comment by cnunciato** [comment]
@scottslowe v0.0.9 (released yesterday) upgraded to @pulumi/pulumi latest, so this should be fixed now. When you have a few, would you mind confirming and closing?

**Comment by scottslowe** [comment]
@cnunciato After removing the old synced-folder resource plugin (via `pulumi plugin rm`), and then using the static website on GCP template (with updated dependencies so it would pull down v0.0.9 of the synced-folder component), I can no longer replicate this issue. I'll perform some additional testing, but for now I'm closing as completed!
