### ISSUE TITLE
synced-folder plugin not available through CDN

### ISSUE THREAD

**Issue by lionello** [pulumi/pulumi-synced-folder#23]
### What happened?

Tried to install using `pulumi plugin install resource synced-folder v0.10.2` and failed with 403. Other plugins are available (unauth'ed) from that CloudFront URL, but `synced-folder` is not.

### Expected Behavior

Expected to be able to download the plugins through the CDN URL (not just GitHub releases)

### Steps to reproduce

* install using `pulumi plugin install resource synced-folder v0.10.2`:
```
error: [resource plugin synced-folder-0.10.2] downloading from : failed to download plugin: synced-folder-0.10.2: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-synced-folder-v0.10.2-darwin-arm64.tar.gz
```
* try `curl`:
```
$ curl -L https://get.pulumi.com/releases/plugins/pulumi-resource-synced-folder-v0.10.2-darwin-arm64.tar.gz                                                                                                                                                                       <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>009YP6GB4NG2AX12</RequestId><HostId>WCQ9uX9fue1eFhUV/m1Ki0WH1EJ3wJh4Sk6U9dszQQXQQeXgaNux6ofmQnAwQtm0chxYh55eIXI=</HostId></Error>                                                                             
```

### Output of `pulumi about`

```
CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Host     
OS       darwin
Version  13.2.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/lionello
User           lionello
Organizations  lionello

Pulumi locates its logs in /var/folders/wp/g4m6l2dx3f71wsy8j6l2wwdc0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lionello** [comment]
I'm still getting the same error. Funnily enough it only happens with this plugin. Other plugins download fine? If it's just on my system, then I might have something weird here, so feel free to close.

**Comment by cnunciato** [comment]
I tried this as well and didn't have any issues, and the usual cause is indeed API rate-limiting on the GitHub end. @lionello does this repro when you have a `GITHUB_TOKEN` environment variable set with a valid GitHub access token?

**Comment by jimjoes** [comment]
I'm getting the same error. No change if I add a valid key to the GITHUB_TOKEN local env var, either.

**Comment by nielskrijger** [comment]
Same issue here. Adding GITHUB_TOKEN doesn't help.

**Comment by nielskrijger** [comment]
Having the same issue, specifically with this plugin. Adding GITHUB_TOKEN doesn't make a difference. Github rate limits are exceeded and the fallback to `get.pulumi.com` fails.

Is there a reason why synced-folder is not available publicly?

**Comment by bensivo** [comment]
I have also experienced this issue, in my case it was within a Gitlab CI pipeline. Because of docker-in-docker we were having to install this plugin on each run.

Would really appreciate a CDN, these rate limits probably don't trigger for anyone doing local development - you only install once. But in CI environments, you end up running installs much more frequently and can easily hit the rate limit if you have multiple projects running on the same agent.

**Comment by cnunciato** [comment]
Binaries for 0.10.2 and 0.11.1 have been published, and future releases should be published automatically.

```
$ pulumi plugin install resource synced-folder v0.11.1 --server https://get.pulumi.com/releases/plugins
[resource plugin synced-folder-0.11.1] installing
Downloading plugin: 45.80 MiB / 45.80 MiB [=========================] 100.00% 3s

$ pulumi plugin ls
NAME           KIND      VERSION  SIZE    INSTALLED      LAST USED
synced-folder  resource  0.11.1   353 MB  8 seconds ago  8 seconds ago
```
